# Generated by Django 4.2.3 on 2023-08-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25)),
                ('l_name', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=2)),
                ('qual', models.CharField(max_length=25)),
                ('sub', models.CharField(max_length=15)),
            ],
        ),
    ]
